# -*- coding: utf-8 -*-
"""Desafio Lighthouse - Dados & AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEQ6xESlgQ_krOhB6JzhGw-kajHIELfe
"""

import pandas as pd

# Importação da base de vendas para análise exploratória (Questão 1)
df_vendas = pd.read_csv('vendas_2023_2024.csv')

# Verificação inicial da estrutura e integridade dos dados
df_vendas.head()

# --- Análise Exploratória e Integridade da Base de Vendas ---

# Dimensões do dataset para conferência de volume
print(f"Total de registros: {df.shape[0]}")
print(f"Total de variáveis (colunas): {df.shape[1]}")

# Tratamento da cronologia: Convertendo sale_date para datetime
# Nota: errors='coerce' utilizado para identificar datas corrompidas durante a carga
df['sale_date'] = pd.to_datetime(df['sale_date'], dayfirst=True, errors='coerce')

print(f"Período analisado: {df['sale_date'].min()} a {df['sale_date'].max()}")
print("-" * 40)

# Métricas descritivas do faturamento (coluna 'total')
print(f"Ticket Mínimo: {df['total'].min()}")
print(f"Ticket Máximo (Outlier): {df['total'].max()}")
print(f"Faturamento Médio por Venda: {df['total'].mean():.2f}")
print("-" * 40)

# Verificação de qualidade: Identificação de Missing Values (Nulos)
# Essencial para validar a confiabilidade dos relatórios para a diretoria
print("Diagnóstico de valores nulos:")
print(df.isnull().sum())

# --- Inspeção de Schema: Validando nomes das colunas e tipos de dados ---
# Este passo é fundamental para garantir a integridade dos Joins e
# evitar erros de referência (KeyError) nas etapas de transformação.

print("Estrutura original do dataset 'produtos_raw':")
print(df_prod.columns.tolist())
print("-" * 30)
print(df_prod.dtypes)

import pandas as pd

# Carga do dataset original para processamento de saneamento
df_prod = pd.read_csv('produtos_raw.csv')

# --- ETAPA 1: Padronização de Categorias (Data Cleaning) ---
# Eliminação de ruídos (espaços em branco) e normalização para minúsculo
df_prod['actual_category'] = df_prod['actual_category'].str.replace(' ', '').str.lower().str.strip()

# Aplicação de lógica de busca por radical (Regex) para corrigir erros de digitação
# Esta abordagem garante que variações como 'eletronicoz' ou 'eletrunicos' sejam unificadas
df_prod.loc[df_prod['actual_category'].str.contains('eletr|eletrun|eletron', na=False), 'actual_category'] = 'eletrônicos'
df_prod.loc[df_prod['actual_category'].str.contains('propul', na=False), 'actual_category'] = 'propulsão'
df_prod.loc[df_prod['actual_category'].str.contains('ancor', na=False), 'actual_category'] = 'ancoragem'

# --- ETAPA 2: Tratamento da Coluna Price (Tipagem de Dados) ---
# Conversão do padrão decimal brasileiro (vírgula) para o padrão computacional (ponto)
# errors='coerce' utilizado para garantir que valores não numéricos não quebrem o processamento
df_prod['price'] = df_prod['price'].astype(str).str.replace(',', '.')
df_prod['price'] = pd.to_numeric(df_prod['price'], errors='coerce')

# --- ETAPA 3: Integridade do Dataset ---
# Remoção de registros redundantes para evitar duplicidade em cálculos de faturamento
df_prod = df_prod.drop_duplicates()

# Validação final do schema e visualização dos dados saneados
print("Saneamento de dados concluído com sucesso.")
print("-" * 40)
print(df_prod.head())
print("-" * 40)
print(f"Total de registros únicos: {len(df_prod)}")

import pandas as pd

# --- Etapa de Saneamento e Normalização do Catálogo de Produtos ---

# Carga do dataset bruto para processamento
df_prod = pd.read_csv('produtos_raw.csv')

# 1. Padronização de Categorias (Data Cleaning)
# Remoção de espaços e normalização de caracteres para unificação de categorias
df_prod['actual_category'] = df_prod['actual_category'].astype(str).str.replace(' ', '').str.lower()

# Aplicação de Regex para correção de inconsistências e erros de digitação (Fuzzy Matching)
df_prod.loc[df_prod['actual_category'].str.contains('eletr|eletrun|eletron', na=False), 'actual_category'] = 'eletrônicos'
df_prod.loc[df_prod['actual_category'].str.contains('propul', na=False), 'actual_category'] = 'propulsão'
df_prod.loc[df_prod['actual_category'].str.contains('ancor', na=False), 'actual_category'] = 'ancoragem'

# 2. Tratamento de Formato Monetário e Tipagem
# Limpeza de strings: Remoção de prefixos de moeda, pontos de milhar e espaços excedentes
df_prod['price'] = df_prod['price'].astype(str).str.replace('R$', '', regex=False).str.replace('.', '', regex=False).str.strip()

# Conversão do separador decimal brasileiro para o padrão internacional (ponto)
df_prod['price'] = df_prod['price'].str.replace(',', '.', regex=False)

# Conversão da coluna para tipo numérico (float) para fins de cálculo
df_prod['price'] = pd.to_numeric(df_prod['price'], errors='coerce')

# 3. Garantia de Integridade
# Eliminação de registros duplicados para assegurar a unicidade do catálogo
df_prod = df_prod.drop_duplicates()

# --- Relatório de Validação Final ---
print("CONFORMIDADE DE DADOS:")
print("-" * 40)
print(df_prod.head())
print("-" * 40)
print(f"Status de integridade (Valores nulos em 'price'): {df_prod['price'].isnull().sum()}")
print(f"Total de SKUs únicos processados: {len(df_prod)}")

import pandas as pd

def processar_catalogo_produtos(caminho_input):
    """
    Realiza o saneamento, normalização e tipagem do catálogo de produtos.
    Focado em integridade de dados para análises financeiras.
    """
    # Carga dos dados brutos
    df = pd.read_csv(caminho_input)

    # 1. Padronização de Categorias (Data Cleaning)
    # Remove espaços internos e padroniza para minúsculo
    df['actual_category'] = df['actual_category'].astype(str).str.replace(' ', '').str.lower()

    # Unificação de categorias via Fuzzy Matching (Busca por radical)
    df.loc[df['actual_category'].str.contains('eletr|eletrun|eletron', na=False), 'actual_category'] = 'eletrônicos'
    df.loc[df['actual_category'].str.contains('propul', na=False), 'actual_category'] = 'propulsão'
    df.loc[df['actual_category'].str.contains('ancor', na=False), 'actual_category'] = 'ancoragem'

    # 2. Tratamento de Formato Monetário (Tipagem de Dados)
    # Limpeza de prefixos (R$), pontos de milhar e espaços
    df['price'] = df['price'].astype(str).str.replace('R$', '', regex=False).str.replace('.', '', regex=False).str.strip()

    # Conversão do separador decimal brasileiro (vírgula) para internacional (ponto)
    df['price'] = df['price'].str.replace(',', '.', regex=False)

    # Casting para tipo numérico (float)
    df['price'] = pd.to_numeric(df['price'], errors='coerce')

    # 3. Integridade e Unicidade
    # Remoção de duplicatas para evitar inflação de faturamento
    df = df.drop_duplicates()

    return df

if __name__ == "__main__":
    # Execução do pipeline de limpeza
    arquivo_alvo = 'produtos_raw.csv'
    df_saneado = processar_catalogo_produtos(arquivo_alvo)

    # Exportação do resultado final
    df_saneado.to_csv('produtos_normalizados.csv', index=False)
    print(f"Processamento concluído. Total de registros: {len(df_saneado)}")